image: node:8.11.4

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

test_dummy:
  stage: test
  script:
   - npm install
   # - npm test
  tags:
    - docker

deploy_ipfs:
  stage: build
  artifacts:
    paths:
      - public
  script:
    - npm install
    - npm install ipfs --global
    - npm run build
    - ipfs add -r public/
  tags:
    - docker
  only:
    - production
