// Events
export const CLEAR_EVENTS = 'CLEAR_EVENTS';

// Whisper
export const GET_WHISPER = 'GET_WHISPER';
export const SEND_WHISPER_MESSAGE = 'SEND_WHISPER_MESSAGE';
export const CREATE_LISTENER = 'CREATE_LISTENER';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SET_WHISPER_PROVIDER = 'SET_WHISPER_PROVIDER';
export const SET_WHISPER = 'SET_WHISPER';
export const CREATE_MESSAGE_FILTER = 'CREATE_MESSAGE_FILTER';

export const UPDATE_WHISPER_IDENTITY = 'UPDATE_WHISPER_IDENTITY';

// Upload
export const FILE_READ = 'FILE_READ';
export const PUSH_FILE_TO_QUEUE = 'PUSH_FILE_TO_QUEUE';
export const CLEAR_FILE_QUEUE = 'CLEAR_FILE_QUEUE';
export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_FINISHED = 'UPLOAD_FINISHED';

// IPFS
export const START_IPFS_ADD_FILE = 'START_IPFS_ADD_FILE';
export const FINISH_IPFS_ADD_FILE = 'FINISH_IPFS_ADD_FILE';


// Download
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const IPFS_GET_FILE = 'IPFS_GET_FILE';

// Encryption
export const GENERATE_ENCRYPTION_KEY = 'GENERATE_ENCRYPTION_KEY';
export const START_ENCRYPT_FILE = 'START_ENCRYPT_FILE';
export const FINISH_ENCRYPT_FILE = 'FINISH_ENCRYPT_FILE';

// Decryption
export const DECRYPT_FILE = 'DECRYPT_FILE';

// Metamask
export const METAMASK_CONNECT = 'METAMASK_CONNECT';
export const METAMASK_LOGIN = 'METAMASK_LOGIN';

// Status
export const NEW_STATUS_INSTANCE = 'NEW_STATUS_INSTANCE';
export const STATUS_CONNECTED = 'STATUS_CONNECT';

// Sidebar
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

// Notification
export const PROCESS_NOTIFICATIONS_QUEUE = 'PROCESS_NOTIFICATIONS_QUEUE';
export const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';